/*

 GAME_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : D:\Users\Imanol\Documents\Repositorios\Sheep-Kaboom_BitBitJam4\res\tiles\bkg_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define game_mapWidth 32
#define game_mapHeight 32
#define game_mapBank 2

extern unsigned char game_map[];

/* End of GAME_MAP.H */
