/*

 STORY_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 32
   Tile set      : D:\Users\Imanol\Documents\Repositorios\Sheep-Kaboom_BitBitJam4\res\tiles\title_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define story_mapWidth 20
#define story_mapHeight 32
#define story_mapBank 2

extern unsigned char story_map[];

/* End of STORY_MAP.H */
