/*

 BOOTTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define BootTilesBank 0

/* Super Gameboy palette 0 */
#define BootTilesSGBPal0c0 6076
#define BootTilesSGBPal0c1 8935
#define BootTilesSGBPal0c2 6596
#define BootTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BootTilesSGBPal1c0 6076
#define BootTilesSGBPal1c1 8935
#define BootTilesSGBPal1c2 6596
#define BootTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BootTilesSGBPal2c0 6076
#define BootTilesSGBPal2c1 8935
#define BootTilesSGBPal2c2 6596
#define BootTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BootTilesSGBPal3c0 6076
#define BootTilesSGBPal3c1 8935
#define BootTilesSGBPal3c2 6596
#define BootTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BootTilesCGBPal0c0 32767
#define BootTilesCGBPal0c1 24311
#define BootTilesCGBPal0c2 14798
#define BootTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define BootTilesCGBPal1c0 32767
#define BootTilesCGBPal1c1 24311
#define BootTilesCGBPal1c2 14798
#define BootTilesCGBPal1c3 31

/* Gameboy Color palette 2 */
#define BootTilesCGBPal2c0 6076
#define BootTilesCGBPal2c1 8935
#define BootTilesCGBPal2c2 6596
#define BootTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define BootTilesCGBPal3c0 6076
#define BootTilesCGBPal3c1 8935
#define BootTilesCGBPal3c2 6596
#define BootTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define BootTilesCGBPal4c0 6076
#define BootTilesCGBPal4c1 8935
#define BootTilesCGBPal4c2 6596
#define BootTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define BootTilesCGBPal5c0 6076
#define BootTilesCGBPal5c1 8935
#define BootTilesCGBPal5c2 6596
#define BootTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define BootTilesCGBPal6c0 6076
#define BootTilesCGBPal6c1 8935
#define BootTilesCGBPal6c2 6596
#define BootTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define BootTilesCGBPal7c0 6076
#define BootTilesCGBPal7c1 8935
#define BootTilesCGBPal7c2 6596
#define BootTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char BootTilesCGB[];
/* Start of tile array. */
extern unsigned char BootTiles[];

/* End of BOOTTILES.H */
