/*

 BOOTMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\elsem\PJs\bitbitjam4\cheapSheep\res\opening\boot.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BootMapWidth 20
#define BootMapHeight 18
#define BootMapBank 0

extern unsigned char BootMap[];

/* End of BOOTMAP.H */
