/*

 FIRESPRITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define fireSpriteBank 0

/* Super Gameboy palette 0 */
#define fireSpriteSGBPal0c0 6076
#define fireSpriteSGBPal0c1 8935
#define fireSpriteSGBPal0c2 6596
#define fireSpriteSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define fireSpriteSGBPal1c0 6076
#define fireSpriteSGBPal1c1 8935
#define fireSpriteSGBPal1c2 6596
#define fireSpriteSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define fireSpriteSGBPal2c0 6076
#define fireSpriteSGBPal2c1 8935
#define fireSpriteSGBPal2c2 6596
#define fireSpriteSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define fireSpriteSGBPal3c0 6076
#define fireSpriteSGBPal3c1 8935
#define fireSpriteSGBPal3c2 6596
#define fireSpriteSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define fireSpriteCGBPal0c0 32767
#define fireSpriteCGBPal0c1 1023
#define fireSpriteCGBPal0c2 31
#define fireSpriteCGBPal0c3 11264

/* Gameboy Color palette 1 */
#define fireSpriteCGBPal1c0 32767
#define fireSpriteCGBPal1c1 1023
#define fireSpriteCGBPal1c2 31
#define fireSpriteCGBPal1c3 12

/* Gameboy Color palette 2 */
#define fireSpriteCGBPal2c0 6076
#define fireSpriteCGBPal2c1 8935
#define fireSpriteCGBPal2c2 6596
#define fireSpriteCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define fireSpriteCGBPal3c0 6076
#define fireSpriteCGBPal3c1 8935
#define fireSpriteCGBPal3c2 6596
#define fireSpriteCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define fireSpriteCGBPal4c0 6076
#define fireSpriteCGBPal4c1 8935
#define fireSpriteCGBPal4c2 6596
#define fireSpriteCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define fireSpriteCGBPal5c0 6076
#define fireSpriteCGBPal5c1 8935
#define fireSpriteCGBPal5c2 6596
#define fireSpriteCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define fireSpriteCGBPal6c0 6076
#define fireSpriteCGBPal6c1 8935
#define fireSpriteCGBPal6c2 6596
#define fireSpriteCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define fireSpriteCGBPal7c0 6076
#define fireSpriteCGBPal7c1 8935
#define fireSpriteCGBPal7c2 6596
#define fireSpriteCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char fireSpriteCGB[];
/* Start of tile array. */
extern unsigned char fireSprite[];

/* End of FIRESPRITE.H */
