/*

 HARDLEVEL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 64
   Tile set      : C:\Users\elsem\PJs\bitbitjam4\cheapSheep\res\tiles2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define HardLevelWidth 64
#define HardLevelHeight 64
#define HardLevelBank 0

extern unsigned char HardLevel[];

/* End of HARDLEVEL.H */
