/*

 HELICOPTERSPRITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 7

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define helicopterSpriteBank 0

/* Super Gameboy palette 0 */
#define helicopterSpriteSGBPal0c0 6076
#define helicopterSpriteSGBPal0c1 8935
#define helicopterSpriteSGBPal0c2 6596
#define helicopterSpriteSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define helicopterSpriteSGBPal1c0 6076
#define helicopterSpriteSGBPal1c1 8935
#define helicopterSpriteSGBPal1c2 6596
#define helicopterSpriteSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define helicopterSpriteSGBPal2c0 6076
#define helicopterSpriteSGBPal2c1 8935
#define helicopterSpriteSGBPal2c2 6596
#define helicopterSpriteSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define helicopterSpriteSGBPal3c0 6076
#define helicopterSpriteSGBPal3c1 8935
#define helicopterSpriteSGBPal3c2 6596
#define helicopterSpriteSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define helicopterSpriteCGBPal0c0 32767
#define helicopterSpriteCGBPal0c1 32736
#define helicopterSpriteCGBPal0c2 32032
#define helicopterSpriteCGBPal0c3 11264

/* Gameboy Color palette 1 */
#define helicopterSpriteCGBPal1c0 6076
#define helicopterSpriteCGBPal1c1 8935
#define helicopterSpriteCGBPal1c2 6596
#define helicopterSpriteCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define helicopterSpriteCGBPal2c0 6076
#define helicopterSpriteCGBPal2c1 8935
#define helicopterSpriteCGBPal2c2 6596
#define helicopterSpriteCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define helicopterSpriteCGBPal3c0 6076
#define helicopterSpriteCGBPal3c1 8935
#define helicopterSpriteCGBPal3c2 6596
#define helicopterSpriteCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define helicopterSpriteCGBPal4c0 6076
#define helicopterSpriteCGBPal4c1 8935
#define helicopterSpriteCGBPal4c2 6596
#define helicopterSpriteCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define helicopterSpriteCGBPal5c0 6076
#define helicopterSpriteCGBPal5c1 8935
#define helicopterSpriteCGBPal5c2 6596
#define helicopterSpriteCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define helicopterSpriteCGBPal6c0 6076
#define helicopterSpriteCGBPal6c1 8935
#define helicopterSpriteCGBPal6c2 6596
#define helicopterSpriteCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define helicopterSpriteCGBPal7c0 6076
#define helicopterSpriteCGBPal7c1 8935
#define helicopterSpriteCGBPal7c2 6596
#define helicopterSpriteCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char helicopterSpriteCGB[];
/* Start of tile array. */
extern unsigned char helicopterSprite[];

/* End of HELICOPTERSPRITE.H */
