/*

 OPENINGTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 120

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define OpeningTilesBank 0

/* Super Gameboy palette 0 */
#define OpeningTilesSGBPal0c0 6076
#define OpeningTilesSGBPal0c1 8935
#define OpeningTilesSGBPal0c2 6596
#define OpeningTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define OpeningTilesSGBPal1c0 6076
#define OpeningTilesSGBPal1c1 8935
#define OpeningTilesSGBPal1c2 6596
#define OpeningTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define OpeningTilesSGBPal2c0 6076
#define OpeningTilesSGBPal2c1 8935
#define OpeningTilesSGBPal2c2 6596
#define OpeningTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define OpeningTilesSGBPal3c0 6076
#define OpeningTilesSGBPal3c1 8935
#define OpeningTilesSGBPal3c2 6596
#define OpeningTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define OpeningTilesCGBPal0c0 32767
#define OpeningTilesCGBPal0c1 20083
#define OpeningTilesCGBPal0c2 14798
#define OpeningTilesCGBPal0c3 5285

/* Gameboy Color palette 1 */
#define OpeningTilesCGBPal1c0 32767
#define OpeningTilesCGBPal1c1 20083
#define OpeningTilesCGBPal1c2 14798
#define OpeningTilesCGBPal1c3 31

/* Gameboy Color palette 2 */
#define OpeningTilesCGBPal2c0 4194
#define OpeningTilesCGBPal2c1 19782
#define OpeningTilesCGBPal2c2 30651
#define OpeningTilesCGBPal2c3 7929

/* Gameboy Color palette 3 */
#define OpeningTilesCGBPal3c0 6076
#define OpeningTilesCGBPal3c1 8935
#define OpeningTilesCGBPal3c2 6596
#define OpeningTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define OpeningTilesCGBPal4c0 6076
#define OpeningTilesCGBPal4c1 8935
#define OpeningTilesCGBPal4c2 6596
#define OpeningTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define OpeningTilesCGBPal5c0 6076
#define OpeningTilesCGBPal5c1 8935
#define OpeningTilesCGBPal5c2 6596
#define OpeningTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define OpeningTilesCGBPal6c0 6076
#define OpeningTilesCGBPal6c1 8935
#define OpeningTilesCGBPal6c2 6596
#define OpeningTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define OpeningTilesCGBPal7c0 6076
#define OpeningTilesCGBPal7c1 8935
#define OpeningTilesCGBPal7c2 6596
#define OpeningTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char OpeningTilesCGB[];
/* Start of tile array. */
extern unsigned char OpeningTiles[];

/* End of OPENINGTILES.H */
