/*

 PRELEVEL1MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\elsem\PJs\bitbitjam4\cheapSheep\res\tiles2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define PreLevel1MapWidth 20
#define PreLevel1MapHeight 18
#define PreLevel1MapBank 0

extern unsigned char PreLevel1Map[];

/* End of PRELEVEL1MAP.H */
