/*

 SHEEPSPRITE.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define sheepSpriteBank 0

/* Super Gameboy palette 0 */
#define sheepSpriteSGBPal0c0 6076
#define sheepSpriteSGBPal0c1 8935
#define sheepSpriteSGBPal0c2 6596
#define sheepSpriteSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define sheepSpriteSGBPal1c0 6076
#define sheepSpriteSGBPal1c1 8935
#define sheepSpriteSGBPal1c2 6596
#define sheepSpriteSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define sheepSpriteSGBPal2c0 6076
#define sheepSpriteSGBPal2c1 8935
#define sheepSpriteSGBPal2c2 6596
#define sheepSpriteSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define sheepSpriteSGBPal3c0 6076
#define sheepSpriteSGBPal3c1 8935
#define sheepSpriteSGBPal3c2 6596
#define sheepSpriteSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define sheepSpriteCGBPal0c0 6076
#define sheepSpriteCGBPal0c1 8935
#define sheepSpriteCGBPal0c2 6596
#define sheepSpriteCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define sheepSpriteCGBPal1c0 6076
#define sheepSpriteCGBPal1c1 8935
#define sheepSpriteCGBPal1c2 6596
#define sheepSpriteCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define sheepSpriteCGBPal2c0 32767
#define sheepSpriteCGBPal2c1 28671
#define sheepSpriteCGBPal2c2 28063
#define sheepSpriteCGBPal2c3 7399

/* Gameboy Color palette 3 */
#define sheepSpriteCGBPal3c0 6076
#define sheepSpriteCGBPal3c1 8935
#define sheepSpriteCGBPal3c2 6596
#define sheepSpriteCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define sheepSpriteCGBPal4c0 6076
#define sheepSpriteCGBPal4c1 8935
#define sheepSpriteCGBPal4c2 6596
#define sheepSpriteCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define sheepSpriteCGBPal5c0 6076
#define sheepSpriteCGBPal5c1 8935
#define sheepSpriteCGBPal5c2 6596
#define sheepSpriteCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define sheepSpriteCGBPal6c0 6076
#define sheepSpriteCGBPal6c1 8935
#define sheepSpriteCGBPal6c2 6596
#define sheepSpriteCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define sheepSpriteCGBPal7c0 6076
#define sheepSpriteCGBPal7c1 8935
#define sheepSpriteCGBPal7c2 6596
#define sheepSpriteCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char sheepSpriteCGB[];
/* Start of tile array. */
extern unsigned char sheepSprite[];

/* End of SHEEPSPRITE.H */
