/*

 SHIPPYTILES2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define ShippyTiles2Bank 0

/* Super Gameboy palette 0 */
#define ShippyTiles2SGBPal0c0 6076
#define ShippyTiles2SGBPal0c1 8935
#define ShippyTiles2SGBPal0c2 6596
#define ShippyTiles2SGBPal0c3 5344

/* Super Gameboy palette 1 */
#define ShippyTiles2SGBPal1c0 6076
#define ShippyTiles2SGBPal1c1 8935
#define ShippyTiles2SGBPal1c2 6596
#define ShippyTiles2SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define ShippyTiles2SGBPal2c0 6076
#define ShippyTiles2SGBPal2c1 8935
#define ShippyTiles2SGBPal2c2 6596
#define ShippyTiles2SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define ShippyTiles2SGBPal3c0 6076
#define ShippyTiles2SGBPal3c1 8935
#define ShippyTiles2SGBPal3c2 6596
#define ShippyTiles2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define ShippyTiles2CGBPal0c0 32767
#define ShippyTiles2CGBPal0c1 21140
#define ShippyTiles2CGBPal0c2 10570
#define ShippyTiles2CGBPal0c3 0

/* Gameboy Color palette 1 */
#define ShippyTiles2CGBPal1c0 339
#define ShippyTiles2CGBPal1c1 992
#define ShippyTiles2CGBPal1c2 480
#define ShippyTiles2CGBPal1c3 3247

/* Gameboy Color palette 2 */
#define ShippyTiles2CGBPal2c0 373
#define ShippyTiles2CGBPal2c1 1331
#define ShippyTiles2CGBPal2c2 2289
#define ShippyTiles2CGBPal2c3 3246

/* Gameboy Color palette 3 */
#define ShippyTiles2CGBPal3c0 5620
#define ShippyTiles2CGBPal3c1 32352
#define ShippyTiles2CGBPal3c2 339
#define ShippyTiles2CGBPal3c3 174

/* Gameboy Color palette 4 */
#define ShippyTiles2CGBPal4c0 32767
#define ShippyTiles2CGBPal4c1 32352
#define ShippyTiles2CGBPal4c2 31
#define ShippyTiles2CGBPal4c3 174

/* Gameboy Color palette 5 */
#define ShippyTiles2CGBPal5c0 32767
#define ShippyTiles2CGBPal5c1 32352
#define ShippyTiles2CGBPal5c2 480
#define ShippyTiles2CGBPal5c3 174

/* Gameboy Color palette 6 */
#define ShippyTiles2CGBPal6c0 736
#define ShippyTiles2CGBPal6c1 32352
#define ShippyTiles2CGBPal6c2 480
#define ShippyTiles2CGBPal6c3 3406

/* Gameboy Color palette 7 */
#define ShippyTiles2CGBPal7c0 32767
#define ShippyTiles2CGBPal7c1 32352
#define ShippyTiles2CGBPal7c2 17735
#define ShippyTiles2CGBPal7c3 5120
/* CGBpalette entries. */
extern unsigned char ShippyTiles2CGB[];
/* Start of tile array. */
extern unsigned char ShippyTiles2[];

/* End of SHIPPYTILES2.H */
