/*

 TESTLEVEL2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 49 x 28
   Tile set      : C:\Users\elsem\PJs\bitbitjam4\cheapSheep\res\tiles2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TestLevel2Width 49
#define TestLevel2Height 28
#define TestLevel2Bank 0

extern unsigned char TestLevel2[];

/* End of TESTLEVEL2.H */
