/*

 TESTWIN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 2
   Tile set      : C:\Users\elsem\PJs\bitbitjam4\cheapSheep\res\tiles2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TestWinWidth 20
#define TestWinHeight 2
#define TestWinBank 0

extern unsigned char TestWin[];

/* End of TESTWIN.H */
