/*

 TITLETILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 159

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define TitleTilesBank 0

/* Super Gameboy palette 0 */
#define TitleTilesSGBPal0c0 6076
#define TitleTilesSGBPal0c1 8935
#define TitleTilesSGBPal0c2 6596
#define TitleTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TitleTilesSGBPal1c0 6076
#define TitleTilesSGBPal1c1 8935
#define TitleTilesSGBPal1c2 6596
#define TitleTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TitleTilesSGBPal2c0 6076
#define TitleTilesSGBPal2c1 8935
#define TitleTilesSGBPal2c2 6596
#define TitleTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TitleTilesSGBPal3c0 6076
#define TitleTilesSGBPal3c1 8935
#define TitleTilesSGBPal3c2 6596
#define TitleTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TitleTilesCGBPal0c0 32767
#define TitleTilesCGBPal0c1 32352
#define TitleTilesCGBPal0c2 14798
#define TitleTilesCGBPal0c3 5285

/* Gameboy Color palette 1 */
#define TitleTilesCGBPal1c0 6076
#define TitleTilesCGBPal1c1 8935
#define TitleTilesCGBPal1c2 6596
#define TitleTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define TitleTilesCGBPal2c0 6076
#define TitleTilesCGBPal2c1 8935
#define TitleTilesCGBPal2c2 6596
#define TitleTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define TitleTilesCGBPal3c0 6076
#define TitleTilesCGBPal3c1 8935
#define TitleTilesCGBPal3c2 6596
#define TitleTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define TitleTilesCGBPal4c0 6076
#define TitleTilesCGBPal4c1 8935
#define TitleTilesCGBPal4c2 6596
#define TitleTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define TitleTilesCGBPal5c0 6076
#define TitleTilesCGBPal5c1 8935
#define TitleTilesCGBPal5c2 6596
#define TitleTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TitleTilesCGBPal6c0 6076
#define TitleTilesCGBPal6c1 8935
#define TitleTilesCGBPal6c2 6596
#define TitleTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define TitleTilesCGBPal7c0 6076
#define TitleTilesCGBPal7c1 8935
#define TitleTilesCGBPal7c2 6596
#define TitleTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char TitleTilesCGB[];
/* Start of tile array. */
extern unsigned char TitleTiles[];

/* End of TITLETILES.H */
