/*

 TITLEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\elsem\PJs\bitbitjam4\cheapSheep\res\title\title.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TitleMapWidth 20
#define TitleMapHeight 18
#define TitleMapBank 0

extern unsigned char TitleMap[];

/* End of TITLEMAP.H */
