/*

 GAMETEXTMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 22 x 6
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define gametextmapWidth 22
#define gametextmapHeight 6
#define gametextmapBank 0

extern unsigned char gametextmap[];

/* End of GAMETEXTMAP.H */
