/*

 INTROMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : introtiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define intromapWidth 40
#define intromapHeight 18
#define intromapBank 0

extern unsigned char intromap[];

/* End of INTROMAP.H */
