/*

 ROOM_02.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 29 x 23
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define room_02Width 29
#define room_02Height 23
#define room_02Bank 0

extern unsigned char room_02[];

/* End of ROOM_02.H */
