/*

 ROOM_01.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 22 x 19
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define room_01Width 22
#define room_01Height 19
#define room_01Bank 0

extern unsigned char room_01[];

/* End of ROOM_01.H */
